### PR TITLE
Structure Pool hopefully fixed

### PR DESCRIPTION
**Pull request by iacuobos**
Didn't do much testing

World starts with 
- qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2
- quilt 0.18.1-beta.23

### CODE REVIEW

**Comment by mrsterner** [comment]
Doesnt build ay

**Comment by iacuobos** [comment]
oh... seems to have failed to download geckolib & midnightlib according to logs

Pretty sure i didn't touch anything gradle related

**Comment by mrsterner** [comment]
I guess i have them cached

**Comment by iacuobos** [comment]
I mean... it worked on my PR that was a _few hours_ before this

I could try again or changing the gradle tho

**Pull request closed without merging**
